### ISSUE TITLE
add asynchronous handler for redux actions and perform an asynchronous action.

### ISSUE THREAD

**Issue by paschalidi** [small-ads/core#23]
* add `thunk` or any other asynchronus handler. 
* use an open api like the one for starwars
* fetch some data, store it in `redux`, and display it in the screen

**Comment by AdrianValdes** [comment]
hi @paschalidi, 
I want to finish this issue because I think it would help me, but to use `redux-thunk` with Typescript is kind of confusing to me. 

Today I made a step back to continue with the Typescript course, it is making me very slow that the sometimes the syntax is still weird to me. I hope it is fine I am taking more time to do it. 

Today I had to spent 4 hours helping the other classmates too. It is a weird contrast to jump from explaining things I understand to fighting the unknown with the project :-)
